---
GENERATOR_VERSION: '1.0'
ANSIBLE_METADATA: |
    {
        'metadata_version': '1.1',
        'status': ['preview'],
        'supported_by': 'community',
        'license': 'Apache 2.0'
    }
NETWORK_OS: sonic
RESOURCE: static_routes
COPYRIGHT: Copyright 2022 Dell Inc. or its subsidiaries. All Rights Reserved
DOCUMENTATION: |
    module: sonic_static_routes
    version_added: 2.0.0
    short_description: Manage static routes configuration on SONiC
    description:
      - This module provides configuration management of static routes for devices running SONiC
    author: "Shade Talabi (@stalabi1)"
    options:
      config:
        type: list
        elements: dict
        description:
          - Manages 'static_routes' configurations
        suboptions:
          vrf_name:
            required: True
            type: str
            description:
              - Name of the configured VRF on the device.
          static_list:
            type: list
            elements: dict
            description:
              - A list of 'static_routes' configurations.
            suboptions:
              prefix:
                required: True
                type: str
                description:
                  - Destination prefix for the static route, either IPv4 or IPv6.
              next_hops:
                type: list
                elements: dict
                description:
                  - A list of next-hops to be utilised for the static route being specified.
                suboptions:
                  index:
                    required: True
                    type: dict
                    description:
                      - An identifier utilised to uniquely reference the next-hop.
                    suboptions:
                      blackhole:
                        type: bool
                        default: False
                        description:
                          - Indicates that packets matching this route should be discarded.
                      interface:
                        type: str
                        description:
                          - The reference to a base interface.
                      nexthop_vrf:
                        type: str
                        description:
                          - Name of the next-hop network instance for leaked routes.
                      next_hop:
                        type: str
                        description:
                          - The next-hop that is to be used for the static route.
                  metric:
                    type: int
                    description:
                      - Specifies the preference of the next-hop entry when it is injected into the RIB.
                  track:
                    type: int
                    description:
                      - The IP SLA track ID for static route.
                  tag:
                    type: int
                    description:
                      - The tag value for the static route.
      state:
        description:
          - The state of the configuration after module completion.
        type: str
        choices:
        - merged
        - deleted
        default: merged
EXAMPLES:
  - deleted_example_01.txt
  - merged_example_01.txt
  - merged_example_02.txt
