# Using "replaced" state to update config

# Before state:
# ------------
#
# sonic# show running-configuration | grep crypto
# crypto trust-store default-ts ca-cert CA2
# crypto security-profile rest
# crypto security-profile trust-store rest default-ts
# crypto security-profile certificate rest host
# crypto security-profile ocsp-list rest http://localhost/ocspa,http://localhost/ocspb
#
---
- name: PKI Replace Test
  hosts: datacenter
  gather_facts: false
  connection: httpapi
  collections:
    - dellemc.enterprise_sonic
  tasks:
    - name: "Replace Config"
      sonic_pki:
        config:
          security-profiles:
            - profile-name: rest
              ocsp-responder-list:
                - http://localhost/ocsp
              revocation-check: false
              trust-store: default-ts
              certificate-name: host
        state: replaced
# After state:
# -----------
#
# sonic# show running-configuration | grep crypto
# crypto trust-store default-ts ca-cert CA2
# crypto security-profile rest
# crypto security-profile trust-store rest default-ts
# crypto security-profile certificate rest host
# crypto security-profile ocsp-list rest http://localhost/ocspa,http://localhost/ocspb
